export const markupCopy = {
  markModeLabel: 'Mark',
  penLabel: 'Pen',
  textLabel: 'Text',
  panLabel: 'Pan',
  clearPageLabel: 'Clear page',
  resetViewLabel: 'Reset view',
  saveFailed: 'Could not save marks. Try again.',
  saveFailedStatus: 'Save failed',
  savingLabel: 'Saving…',
  savedLabel: 'Saved',
  showAllLayersLabel: 'All',
  showMineOnlyLabel: 'Mine',
  marksUnavailable:
    'Marks unavailable — if self-hosting, run database migrations (alembic upgrade head).',
  marksUnavailableShort: 'Marks unavailable.',
  layerVisible: 'Show layer',
  penSizeFine: 'Fine',
  penSizeMedium: 'Medium',
  penSizeBold: 'Bold',
  undoLabel: 'Undo',
  loupeLabel: 'Magnifier',
  loupeTooltip: 'Click the image to place the magnifier, then draw inside it',
  loupePlaceHint: 'Click the image to place the magnifier',
  stampLabel: 'Stamp',
  stampMissingHint: 'Add a saved stamp in Settings → General',
  stampPlaceHint:
    'Click to place · drag to move · handles to resize/rotate · Delete to remove',
  markupPointBudgetExceeded: 'Markup is too large to save (point limit reached).',
} as const;
