import type { Project, ProjectStatus } from '@/types/project';
import type { ProjectComponent } from '@/types/projectComponent';
import type { ProjectComponentNote } from '@/types/projectComponentNote';
import type { ProjectComponentTask } from '@/types/projectComponentTask';
import type { ProjectMember } from '@/types/project';
import type { ProjectEvent } from '@/types/project';
import type { ProjectLayoutMode } from './projectLayoutModes';
import type { ProjectComponentTotalCostResponse } from '@/types/ledger';

export interface ProjectsPageLayoutProps {
  layout: ProjectLayoutMode;
  onLayoutChange: (mode: ProjectLayoutMode) => void;
  filteredProjects: Project[];
  loadingProjects: boolean;
  selectedProjectId: number | null;
  components: ProjectComponent[];
  loadingComponents: boolean;
  selectedComponentId: number | null;
  selectedProject: Project | null;
  selectedComponent: ProjectComponent | undefined;
  projectMembers: ProjectMember[];
  currentUserId: number | null;
  projectEvents: ProjectEvent[];
  componentItems: { id: number; item_id: number; qty: number }[];
  miscCosts: { id: number; name: string; amount: number }[];
  componentNotes: ProjectComponentNote[];
  tasks: ProjectComponentTask[];
  totalCost: ProjectComponentTotalCostResponse | undefined;
  leftGroupTab: 'items' | 'misc';
  rightGroupTab: 'notes' | 'tasks' | 'documents';
  isDeletingProject: boolean;
  isDeletingComponent: boolean;
  onProjectSelect: (project: Project) => void;
  onClearProjectSelection: () => void;
  onComponentSelect: (component: ProjectComponent) => void;
  onAddProject: () => void;
  onAddComponent: () => void;
  onDeleteProject: (project: Project) => void;
  onDeleteComponent: (component: ProjectComponent) => void;
  onManageMembers: () => void;
  onEditProject: () => void;
  onEditComponent: () => void;
  onLeftGroupTabChange: (tab: 'items' | 'misc') => void;
  onRightGroupTabChange: (tab: 'notes' | 'tasks' | 'documents') => void;
  onLeftGroupAdd: () => void;
  onAddNote: () => void;
  onAddTask: () => void;
  onOpenNote: (note: ProjectComponentNote) => void;
  onDeleteNote: (note: ProjectComponentNote) => void;
  onToggleTask: (taskId: number, isCompleted: boolean) => void;
  onDeleteTask: (task: ProjectComponentTask) => void;
  getItemName: (itemId: number) => string;
  statusFilter?: ProjectStatus | 'all';
}
