import type { AppNotification } from './notificationTypes';

const hoursAgo = (h: number) => new Date(Date.now() - h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n-1',
    kind: 'approval_pending',
    severity: 'urgent',
    title: 'PO-1042 needs your approval',
    body: 'Purchase order is ready for review — 3 sections confirmed, 2 of 3 approvals collected.',
    href: '/orders/purchase',
    createdAt: hoursAgo(1),
    entityRef: 'PO-1042',
  },
  {
    id: 'n-2',
    kind: 'approval_assigned',
    severity: 'action',
    title: 'You were added as approver on EXP-003',
    body: 'Utilities expense order · $1,240 total · assigned by Alex Chen.',
    href: '/orders/expense',
    createdAt: hoursAgo(2),
    entityRef: 'EXP-003',
  },
  {
    id: 'n-3',
    kind: 'section_confirm',
    severity: 'action',
    title: 'Confirm expenses on TO-891',
    body: 'Transfer order items need confirmation before approvals can proceed.',
    href: '/orders/transfer',
    createdAt: hoursAgo(4),
    entityRef: 'TO-891',
  },
  {
    id: 'n-4',
    kind: 'invoice_action',
    severity: 'action',
    title: 'Draft invoice ready on PO-1042',
    body: 'Linked payable invoice is in draft — confirm when supplier details look correct.',
    href: '/orders/purchase',
    createdAt: hoursAgo(5),
    entityRef: 'PO-1042',
  },
  {
    id: 'n-5',
    kind: 'approval_pending',
    severity: 'urgent',
    title: 'TO-772 needs your approval',
    body: 'Transfer order between Main Warehouse and Line B — awaiting your sign-off.',
    href: '/orders/transfer',
    createdAt: hoursAgo(8),
    entityRef: 'TO-772',
  },
  {
    id: 'n-6',
    kind: 'low_stock',
    severity: 'urgent',
    title: 'Widget A below reorder point',
    body: 'On-hand 12 units · reorder at 25 · last movement 2 days ago.',
    href: '/storage',
    createdAt: hoursAgo(12),
    entityRef: 'Widget A',
  },
  {
    id: 'n-7',
    kind: 'project_update',
    severity: 'info',
    title: 'Project Alpha deadline in 3 days',
    body: '2 components still in planning · 1 task overdue.',
    href: '/project',
    createdAt: daysAgo(1),
    entityRef: 'Project Alpha',
  },
  {
    id: 'n-8',
    kind: 'maintenance',
    severity: 'action',
    title: 'CNC-01 maintenance due tomorrow',
    body: 'Scheduled service in Assembly · section Bay 2.',
    href: '/factories',
    createdAt: daysAgo(1),
    entityRef: 'CNC-01',
  },
  {
    id: 'n-9',
    kind: 'approval_assigned',
    severity: 'action',
    title: 'You were added as approver on EXP-007',
    body: 'Payroll expense · due next Friday.',
    href: '/orders/expense',
    createdAt: daysAgo(2),
    entityRef: 'EXP-007',
  },
  {
    id: 'n-10',
    kind: 'system',
    severity: 'info',
    title: 'New workspace member joined',
    body: 'Jordan Lee accepted the invitation and can now access this workspace.',
    href: '/management',
    createdAt: daysAgo(3),
  },
  {
    id: 'n-11',
    kind: 'low_stock',
    severity: 'info',
    title: 'Steel rod 12mm running low',
    body: 'On-hand 48 m · reorder at 50 m.',
    href: '/storage',
    createdAt: daysAgo(4),
  },
  {
    id: 'n-12',
    kind: 'invoice_action',
    severity: 'info',
    title: 'Invoice confirmed on EXP-001',
    body: 'Expense order invoice finalized — ready for payment scheduling.',
    href: '/orders/expense',
    createdAt: daysAgo(5),
    entityRef: 'EXP-001',
  },
];
